### ISSUE TITLE
Upgrading a backpack causes it to lose all contents

### ISSUE THREAD

**Issue by Draskh** [Flanks255/simplybackpacks#3] opened 2019-08-31 17:12 UTC
**Describe the bug**
Upgrading deltes all items inside the backpack.

**Comment by Flanks255** [comment] 2019-08-31 17:46
Can you give me some more information?
Is this in single or multiplayer?
what mod version, forge version.
is this in a modpack? if so which one.

cause so far i cant reproduce it.

**Comment by Draskh** [comment] 2019-09-02 19:28
I use Forge 2838 in singleplayer. I upgraded from to an Epic Backpack if this helps. And I have Bauble installed. 

Here is complete list of mods.
[mods.txt](https://github.com/Flanks255/simplybackpacks/files/3566985/mods.txt)

**Comment by Flanks255** [comment] 2019-09-02 19:35
what kinda crafting table was it in? normal, tinkers AE2 terminal?

**Comment by Draskh** [comment] 2019-09-02 19:47
I used a AE2 Crafting Terminal.

**Comment by Flanks255** [comment] 2020-08-24 00:18
I'm not sure where along the line AE2 fixed the bug, but, its confirmed fixed in 1.16.1

**Closed as completed by Flanks255** 2020-08-24 00:18 UTC
Labels: mod interaction
